name: pr

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
